package com.fourace.android.data;

import java.util.Date;

import android.content.ContentValues;
import android.database.Cursor;

import com.fourace.android.Constants.LogLevel;
import com.fourace.android.Utils;

public class NewsItem {
	//**************************************************************************************************************************************************
	//**************************************************************************************************************************************************
	//****** BEGIN AUTOGENERATED CODE - 2013-12-30 21:22:43*********************************************************************************************
	//**************************************************************************************************************************************************
	//**************************************************************************************************************************************************

    protected static final String DATABASE_TABLE_NAME = "dbo_NewsItem";

	public NewsItem() {
		_newsItemID = 0;
		_title = "";
		_content = "";
		_timestamp = new Date();
	}

	private int _newsItemID;
	public int getNewsItemID()                { return _newsItemID; }
	public void setNewsItemID( int val )      { _newsItemID = val; }

	private String _title;
	public String getTitle()                { return _title; }
	public void setTitle( String val )      { _title = val; }

	private String _content;
	public String getContent()                { return _content; }
	public void setContent( String val )      { _content = val; }

	private Date _timestamp;
	public Date getTimestamp()                { return _timestamp; }
	public void setTimestamp( Date val )      { _timestamp = val; }

	protected static String getTableDefinition() {
		StringBuilder tableBuilder = new StringBuilder();
		tableBuilder.append( "CREATE TABLE " );
		tableBuilder.append( DATABASE_TABLE_NAME );
		tableBuilder.append( "( " );
		tableBuilder.append( "newsItemID integer PRIMARY KEY NOT NULL," );
		tableBuilder.append( "title varchar(32) NOT NULL," );
		tableBuilder.append( "content varchar(1024) NOT NULL," );
		tableBuilder.append( "timestamp datetime NOT NULL" );
		tableBuilder.append( " );" );
		return tableBuilder.toString();
	}

	private ContentValues createContentValues() {
		ContentValues cv = new ContentValues();

		cv.put( "newsItemID", this.getNewsItemID() );
		cv.put( "title", this.getTitle() );
		cv.put( "content", this.getContent() );
		cv.put( "timestamp", this.getTimestamp() == null ? null : Utils.formatDateTime( this.getTimestamp() ) );

		return cv;
	}

	private static NewsItem loadFromCursor( Cursor cursor ) {

		try {
			NewsItem retval = new NewsItem();
			int i = 0;
			retval.setNewsItemID( cursor.getInt( i ) );
			++i;
			retval.setTitle( cursor.getString( i ) );
			++i;
			retval.setContent( cursor.getString( i ) );
			++i;
			retval.setTimestamp( Utils.parseDateTime( cursor.getString( i ) ) );
			++i;

			return retval;
		}
		catch ( Exception exception ) {
			ErrorLog.log( LogLevel.ERROR, "NewsItem", "loadFromCursor", "Unhandled exception loading from cursor", exception );
		}
		return null;
	}

	//**************************************************************************************************************************************************
	//**************************************************************************************************************************************************
	//****** END AUTOGENERATED CODE ********************************************************************************************************************
	//**************************************************************************************************************************************************
	//**************************************************************************************************************************************************
}
